name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Publish
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        env:
          CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN || 'libcuda.so' }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{secrets.CF_ACCOUNT_ID}}
          vars:
            CUSTOM_DOMAIN
          command: deploy --env production --minify src/index.js
          environment: production
          
